apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: docker.io/library/httpd:2.4.41
        ports:
        - containerPort: 80
