apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: image-registry.openshift-image-registry.svc:5000/openshift/testbuilds/httpd:latest  
        ports:
        - containerPort: 80
